/*
 * Elepheye
 *
 * Copyright (c) 2009 Michito Kaji
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

#ifndef ELEPHEYE_RESOURCE_H
#define ELEPHEYE_RESOURCE_H

#define ELEPHEYE_RESOURCE_IDS_ISSUE_ALLOCATE_MEMORY 1001
#define ELEPHEYE_RESOURCE_IDS_ISSUE_CLOSE_HANDLE 1002
#define ELEPHEYE_RESOURCE_IDS_ISSUE_COMPARE_RECORDS 1003
#define ELEPHEYE_RESOURCE_IDS_ISSUE_COMPUTE_HASH 1004
#define ELEPHEYE_RESOURCE_IDS_ISSUE_CREATE_FILTER 1005
#define ELEPHEYE_RESOURCE_IDS_ISSUE_CREATE_SOURCE 1006
#define ELEPHEYE_RESOURCE_IDS_ISSUE_DISABLE_PRIVILEGE 1007
#define ELEPHEYE_RESOURCE_IDS_ISSUE_ENABLE_PRIVILEGE 1008
#define ELEPHEYE_RESOURCE_IDS_ISSUE_FIND_DIRECTORY_CONTENTS 1009
#define ELEPHEYE_RESOURCE_IDS_ISSUE_FIND_FILE_STREAMS 1010
#define ELEPHEYE_RESOURCE_IDS_ISSUE_FIND_REGISTRY_SUB_KEYS 1011
#define ELEPHEYE_RESOURCE_IDS_ISSUE_FIND_REGISTRY_VALUES 1012
#define ELEPHEYE_RESOURCE_IDS_ISSUE_OPEN_FILE 1013
#define ELEPHEYE_RESOURCE_IDS_ISSUE_OPEN_REGISTRY_KEY 1014
#define ELEPHEYE_RESOURCE_IDS_ISSUE_PARSE_CSV 1015
#define ELEPHEYE_RESOURCE_IDS_ISSUE_PARSE_RULE 1016
#define ELEPHEYE_RESOURCE_IDS_ISSUE_READ_DACL 1017
#define ELEPHEYE_RESOURCE_IDS_ISSUE_READ_FILE 1018
#define ELEPHEYE_RESOURCE_IDS_ISSUE_READ_FILESYSTEM 1019
#define ELEPHEYE_RESOURCE_IDS_ISSUE_READ_GROUP 1020
#define ELEPHEYE_RESOURCE_IDS_ISSUE_READ_OWNER 1021
#define ELEPHEYE_RESOURCE_IDS_ISSUE_READ_RECORD 1022
#define ELEPHEYE_RESOURCE_IDS_ISSUE_READ_REGISTRY 1023
#define ELEPHEYE_RESOURCE_IDS_ISSUE_READ_SACL 1024
#define ELEPHEYE_RESOURCE_IDS_ISSUE_READ_TEXT 1025
#define ELEPHEYE_RESOURCE_IDS_ISSUE_READ_WMI 1026
#define ELEPHEYE_RESOURCE_IDS_ISSUE_UNEXPECTED 1027
#define ELEPHEYE_RESOURCE_IDS_ISSUE_WRITE_FILE 1028
#define ELEPHEYE_RESOURCE_IDS_REASON_INVALID_ARGUMENT 1029
#define ELEPHEYE_RESOURCE_IDS_REASON_INVALID_CHARACTER 1030
#define ELEPHEYE_RESOURCE_IDS_REASON_INVALID_DOUBLE_QUOTE 1031
#define ELEPHEYE_RESOURCE_IDS_REASON_INVALID_PATH 1032
#define ELEPHEYE_RESOURCE_IDS_REASON_INVALID_TOKEN 1033
#define ELEPHEYE_RESOURCE_IDS_REASON_KEY_FIELD_NOT_SORTED 1034
#define ELEPHEYE_RESOURCE_IDS_REASON_KEY_FIELD_NOT_UNIQUE 1035
#define ELEPHEYE_RESOURCE_IDS_REASON_MISMATCHED_FIELD_COUNT 1036
#define ELEPHEYE_RESOURCE_IDS_REASON_MISMATCHED_FIELD_NAME 1037
#define ELEPHEYE_RESOURCE_IDS_REASON_MISSING_ARGUMENTS 1038
#define ELEPHEYE_RESOURCE_IDS_REASON_MISSING_BOM 1039
#define ELEPHEYE_RESOURCE_IDS_REASON_MISSING_CLOSING_DOUBLE_QUOTE 1040
#define ELEPHEYE_RESOURCE_IDS_REASON_MISSING_COMMANDS 1041
#define ELEPHEYE_RESOURCE_IDS_REASON_MISSING_FIELDS 1042
#define ELEPHEYE_RESOURCE_IDS_REASON_MISSING_FIELD_NAME 1043
#define ELEPHEYE_RESOURCE_IDS_REASON_MISSING_MATCH_PATTERN 1044
#define ELEPHEYE_RESOURCE_IDS_REASON_MISSING_OPTION_NAME 1045
#define ELEPHEYE_RESOURCE_IDS_REASON_MISSING_WMI_PATH 1046
#define ELEPHEYE_RESOURCE_IDS_REASON_TOO_MANY_ARGUMENTS 1047
#define ELEPHEYE_RESOURCE_IDS_REASON_UNEXPECTED_EOF 1048
#define ELEPHEYE_RESOURCE_IDS_REASON_UNKNOWN_COMMAND 1049
#define ELEPHEYE_RESOURCE_IDS_REASON_UNKNOWN_FIELD_NAME 1050
#define ELEPHEYE_RESOURCE_IDS_REASON_UNKNOWN_FILTER_TYPE 1051
#define ELEPHEYE_RESOURCE_IDS_REASON_UNKNOWN_MATCH_OPTION 1052
#define ELEPHEYE_RESOURCE_IDS_REASON_UNKNOWN_OPTION_NAME 1053
#define ELEPHEYE_RESOURCE_IDS_REASON_UNKNOWN_SOURCE_TYPE 1054

#endif /* #ifndef ELEPHEYE_RESOURCE_H */
